### ISSUE TITLE
Implement Women & Web Lit Site

### ISSUE THREAD

**Issue by flukeout** [mozilla/womenandweb#13]
We are moving forward with this design...
- https://redpen.io/pg566c3520217fb839

We're still deciding some aspects of the intro text treatment, but it's not important.

**Plan of Attack**
- [x] @gvn will set up the necessary HTML scaffolding and markdown files
  - Includes setting up columns where necessary
  - Use placeholder content roughly in the length of what is in the design
- [x] @flukeout will populate with final content and style the page
- [x] @amirad will dig up Collaborator logos
- [x] @amirad to shorten the 2 existing Blog Post descriptions
- [x] @amirad to provide 3rd piece of content for Inclusion section
  - Where the two existing blog posts are

Some extra files
- [Annotated PDF with some HEX values](https://www.dropbox.com/s/srlw4o9oz9dx5pj/wwl-designs-final-annotated.pdf?dl=0)
- [Source Illustrator File](https://dl.dropboxusercontent.com/u/109902/wwl/wwl-designs-final.ai)

**Comment by amirad** [comment]
Great! I emailed 6 orgs to ask for links/logos. Will share them as they come in. 

Will update blogs/descriptions soon.

**Comment by amirad** [comment]
Update: Have two logos - still waiting to hear back on other four. 

Web Foundation - WF logo is downloadable here http://webfoundation.org/wp-content/uploads/2015/05/11434_wf_logo_cmyk_ill91.psd and the site to link to would be this one: http://webfoundation.org/our-work/projects/womens-rights-online/ 

DOT - logo is here https://drive.google.com/open?id=0B5CSa8l3sstMT1BkTDlibGpxTzc4ODFYTjd3Q2JJdjJQRExZ and link is http://dotrust.org

D+I SECTION 

Title: Update on the United Nations High Level Panel
Text: Mitchell Baker joined the UN Secretary-General’s High-Level Panel on Women’s Economic Empowerment in Costa Rica to prepare the first draft of the panel’s report which showcases successful programs and practices in women’s economic empowerment.
Link: https://blog.lizardwrangler.com/2016/07/22/update-on-the-united-nations-high-level-panel-on-womens-economic-empowerment/

Title: STEMM Role Models
Text: The STEMM Role Models App is a database that conference organizers could use to widen their reach when considering which researchers to invite to speak or to sit on panels. 
Link: https://science.mozilla.org/projects/KirstieJane-STEMMRoleModels

Title: Diversity and Inclusion Summit in NYC
Text: Hive NYC partnered with New York's City Council to present the Digital Inclusion Summit on August 16, 2016 to bring together stakeholders in a conversation about the future of voter engagement, female activism, Participatory Budgeting, and more. 
Link: NO LINK

**Comment by amirad** [comment]
Six logo's can be found here: https://drive.google.com/a/mozilla.com/folderview?id=0B5CSa8l3sstMeUlUSFpsRk41Yzg&usp=sharing
Still working on approving 1-2 of them but they should be fine. 

Links for logos:
Web Foundation: http://webfoundation.org/our-work/projects/womens-rights-online/
ITU: http://www.itu.int/en/Pages/default.aspx 
Digital Opportunity Trust: https://www.dotrust.org/
UN Women: http://www.unwomen.org 
World Pulse: http://worldpulse.com/
Empower Women: http://empowerwomen.org/

**Comment by flukeout** [comment]
@amirad Actually, I can just find the logos online, so don't worry about hunting them down. In the [content doc](https://docs.google.com/document/d/1ehB2zgBH6XIAif6rUyLyHmGWQQSdQrxQpounPk9bPI8/edit#) there are 5 collaborators listed. I have 

* [x] UN Women
* [x] Web Foundation 
* [x] Digital Opportunity Trust
* [ ] ITU <- what org is this??
* [ ] World Pule <- what org is this??

**Comment by amirad** [comment]
@flukeout I got all the logos though - they're in that doc I linked to! There are 6 logos total!

And my last comment had all the links to the pages with their names on it. My last post has the correct names of the orgs too.

**Comment by flukeout** [comment]
@amirad wow - how did I miss that, I'm a dork, sorry!!

**Comment by amirad** [comment]
ha! It's okay. I thought you might have missed it.

**Comment by flukeout** [comment]
Filed PR #27 with all of the updates. Will create a follow up issue to QA the content & design from a staging URL.
